### PR TITLE
JoshgunBranch

### PR DESCRIPTION
**Pull request by joshguna**

### CODE REVIEW

**Review by aysuahmadli — APPROVED** [review]
Looks great! Let's merge!

**Review by bakhtiyar-eyvazov — APPROVED** [review]
good job

**Review by fredik90 — APPROVED** [review]
Joshgun submitted

**Review by Sabirindev — CHANGES_REQUESTED** [review]
please and two more primitive data type

**Review by joshguna — COMMENTED** [review]
review edin zehmet olmasa

**Review by aysuahmadli — APPROVED** [review]
Good job!

**Review by fredik90 — APPROVED** [review]
that's great

**Review by fredik90 — APPROVED** [review]
Also would like submit

**Review by Sabirindev — APPROVED** [review]

**Pull request merged**
